export type WineColor = "红葡萄酒" | "白葡萄酒" | "桃红葡萄酒";

export interface Wine {
  id: string;
  /** 盲品编号，不含产区/品种信息，避免提前泄题 */
  code: string;
  region: string;
  grape: string;
  color: WineColor;
  appearance: string;
  acidity: string;
  tannin: string;
  body: string;
  alcohol: string;
  /** 出题阶段可见的感官线索 */
  clues: string[];
  /** 作答后揭晓的典型香气 */
  aromas: string[];
  /** 揭晓时的品鉴要点 */
  notes: string;
}

/** 题库产区（左侧训练队列） */
export const REGIONS = [
  "波尔多",
  "勃艮第",
  "纳帕",
  "里奥哈",
  "香槟",
  "巴罗洛",
  "基安帝",
  "摩泽尔",
  "马尔堡",
  "北罗讷",
] as const;

export const ALL_REGION_OPTION = "全部产区";

export const GRAPE_OPTIONS = [
  "赤霞珠",
  "梅洛",
  "黑皮诺",
  "丹魄",
  "霞多丽",
  "长相思",
  "西拉",
  "内比奥罗",
  "桑娇维塞",
  "雷司令",
] as const;

export const WINES: Wine[] = [
  {
    id: "bx-left-bank",
    code: "样酒 01",
    region: "波尔多",
    grape: "赤霞珠",
    color: "红葡萄酒",
    appearance: "深宝石红带紫边",
    acidity: "中高",
    tannin: "高",
    body: "饱满",
    alcohol: "中高",
    clues: ["高单宁，抓口感明显", "中高酸，结构硬朗", "酒体饱满，陈年潜力强"],
    aromas: ["黑醋栗", "雪松", "铅笔芯", "黑樱桃"],
    notes: "左岸砾石地以赤霞珠为主，常混酿少量梅洛，橡木桶带来雪松与烟熏气息。",
  },
  {
    id: "bx-right-bank",
    code: "样酒 02",
    region: "波尔多",
    grape: "梅洛",
    color: "红葡萄酒",
    appearance: "深宝石红，色泽柔和",
    acidity: "中",
    tannin: "中高",
    body: "中等到饱满",
    alcohol: "中高",
    clues: ["单宁圆润，熟果感强", "酸度中等，口感柔顺", "酒精度偏高，质地绵密"],
    aromas: ["李子干", "黑樱桃", "巧克力", "薄荷"],
    notes: "右岸黏土地以梅洛为主，比左岸更早适饮，果味熟甜、单宁丝滑。",
  },
  {
    id: "bg-village",
    code: "样酒 03",
    region: "勃艮第",
    grape: "黑皮诺",
    color: "红葡萄酒",
    appearance: "浅宝石红，边缘砖红",
    acidity: "高",
    tannin: "低到中",
    body: "中等",
    alcohol: "中",
    clues: ["颜色浅，单宁细致", "高酸贯穿始终", "杯中逐渐出现森林地表气息"],
    aromas: ["红樱桃", "蘑菇", "湿叶", "香料"],
    notes: "黑皮诺果穗小皮薄，色浅但香气层次复杂，陈年发展出动植物与松露气息。",
  },
  {
    id: "bg-chablis",
    code: "样酒 04",
    region: "勃艮第",
    grape: "霞多丽",
    color: "白葡萄酒",
    appearance: "浅柠檬黄",
    acidity: "高",
    tannin: "无",
    body: "清瘦到中等",
    alcohol: "中",
    clues: ["高酸爽口，酒体清瘦", "几乎无橡木影响", "杯口有明显矿物咸鲜感"],
    aromas: ["青苹果", "柑橘", "白桃", "燧石"],
    notes: "夏布利的启莫里阶石灰岩赋予霞多丽独特的燧石矿物感，传统酿造不过桶。",
  },
  {
    id: "np-cab",
    code: "样酒 05",
    region: "纳帕",
    grape: "赤霞珠",
    color: "红葡萄酒",
    appearance: "深紫红，近乎不透光",
    acidity: "中",
    tannin: "高但柔顺",
    body: "饱满",
    alcohol: "高",
    clues: ["酒体浓郁，酒精度常超 14%", "果酱般的熟果风格", "新橡木痕迹明显"],
    aromas: ["黑醋栗果酱", "橡木", "香草", "桉树"],
    notes: "纳帕谷温暖日照让赤霞珠完全成熟，风格丰腴，新橡木与高酒精是标志性线索。",
  },
  {
    id: "np-chard",
    code: "样酒 06",
    region: "纳帕",
    grape: "霞多丽",
    color: "白葡萄酒",
    appearance: "深柠檬黄带金",
    acidity: "中",
    tannin: "无",
    body: "饱满",
    alcohol: "中高",
    clues: ["酒体饱满圆润", "明显奶油与烘烤香气", "苹果酸乳酸发酵痕迹重"],
    aromas: ["黄油", "烤榛子", "菠萝", "香草"],
    notes: "加州风格霞多丽常经木桶发酵与搅桶，热带水果和奶油爆米花香气突出。",
  },
  {
    id: "lj-crianza",
    code: "样酒 07",
    region: "里奥哈",
    grape: "丹魄",
    color: "红葡萄酒",
    appearance: "石榴红带砖边",
    acidity: "中",
    tannin: "中",
    body: "中等",
    alcohol: "中高",
    clues: ["美国橡木桶痕迹突出", "果味与三类香气并存", "单宁柔和，易入口"],
    aromas: ["香草", "椰子", "熟李子", "烟草"],
    notes: "里奥哈传统风格长期在美国橡木桶中陈酿，香草椰子是辨别丹魄的关键线索。",
  },
  {
    id: "lj-rosado",
    code: "样酒 08",
    region: "里奥哈",
    grape: "丹魄",
    color: "红葡萄酒",
    appearance: "深石榴红",
    acidity: "中高",
    tannin: "中高",
    body: "中等到饱满",
    alcohol: "中高",
    clues: ["黑色果味比传统里奥哈更新鲜", "橡木与果味平衡", "结构感比陈酿级更强"],
    aromas: ["黑莓", "蓝莓", "甘草", "烘烤香料"],
    notes: "里奥哈现代风格缩短橡木陈酿、突出丹魄本色的深色水果与甘草。",
  },
  {
    id: "xp-brut",
    code: "样酒 09",
    region: "香槟",
    grape: "霞多丽",
    color: "白葡萄酒",
    appearance: "浅柠檬黄，气泡细密持久",
    acidity: "高",
    tannin: "无",
    body: "中等",
    alcohol: "中",
    clues: ["气泡绵密，慕斯感强", "高酸但口感圆润", "明显酒泥自溶风味"],
    aromas: ["柑橘", "白花", "烤面包", "奶酪皮"],
    notes: "白中白香槟以霞多丽酿造，陈年后的烤面包与坚果气息来自酒泥接触。",
  },
  {
    id: "xp-rose",
    code: "样酒 10",
    region: "香槟",
    grape: "黑皮诺",
    color: "桃红葡萄酒",
    appearance: "浅铜粉色，气泡细腻",
    acidity: "高",
    tannin: "低",
    body: "中等",
    alcohol: "中",
    clues: ["桃红起泡，带极轻微单宁结构", "红色水果气泡感", "瓶中二次发酵风味"],
    aromas: ["草莓", "红莓", "山楂", "饼干"],
    notes: "桃红香槟靠黑皮诺浸皮或静态红酒调配取得颜色与红果骨架。",
  },
  {
    id: "bl-barolo",
    code: "样酒 11",
    region: "巴罗洛",
    grape: "内比奥罗",
    color: "红葡萄酒",
    appearance: "浅石榴红，边缘橙砖色",
    acidity: "高",
    tannin: "高",
    body: "饱满",
    alcohol: "高",
    clues: ["色浅却单宁惊人", "高酸高单宁高酒精三重结构", "玫瑰与焦油香气极具辨识度"],
    aromas: ["玫瑰", "焦油", "干樱桃", "松露"],
    notes: "内比奥罗果皮薄色浅，但单宁与酸度极强，陈年数十年仍有骨架。",
  },
  {
    id: "ja-chianti",
    code: "样酒 12",
    region: "基安帝",
    grape: "桑娇维塞",
    color: "红葡萄酒",
    appearance: "中宝石红，偏砖红",
    acidity: "高",
    tannin: "中高",
    body: "中等",
    alcohol: "中高",
    clues: ["高酸爽口，单宁带颗粒感", "红色酸果为主调", "常带草本与泥土气息"],
    aromas: ["酸樱桃", "番茄叶", "紫罗兰", "皮革"],
    notes: "桑娇维塞高酸、酒体中等，番茄梗与酸樱桃是意大利餐酒的典型线索。",
  },
  {
    id: "mz-riesling",
    code: "样酒 13",
    region: "摩泽尔",
    grape: "雷司令",
    color: "白葡萄酒",
    appearance: "极浅柠檬绿",
    acidity: "极高",
    tannin: "无",
    body: "轻到中等",
    alcohol: "低到中",
    clues: ["酸度尖锐，余味咸鲜", "酒体轻，常带残糖平衡", "明显汽油与白桃气息"],
    aromas: ["白桃", "柠檬皮", "汽油", "洋甘菊"],
    notes: "板岩陡坡上的雷司令矿物感突出， Kabinett 级别常低酒精、带轻盈残糖。",
  },
  {
    id: "me-sb",
    code: "样酒 14",
    region: "马尔堡",
    grape: "长相思",
    color: "白葡萄酒",
    appearance: "浅柠檬黄带绿",
    acidity: "高",
    tannin: "无",
    body: "中等",
    alcohol: "中高",
    clues: ["香气奔放扑鼻", "高酸，几乎不带橡木", "青草与热带水果并存"],
    aromas: ["百香果", "接骨木花", "青草", "猫尿"],
    notes: "新西兰马尔堡长相思以直白浓烈的热带水果和草本香气著称。",
  },
  {
    id: "nr-rotie",
    code: "样酒 15",
    region: "北罗讷",
    grape: "西拉",
    color: "红葡萄酒",
    appearance: "深黑紫红，几乎不透明",
    acidity: "中高",
    tannin: "高",
    body: "饱满",
    alcohol: "高",
    clues: ["颜色深黑，单宁扎实", "黑胡椒辛香料突出", "常有烟熏肉类气息"],
    aromas: ["黑莓", "黑胡椒", "紫罗兰", "熏肉"],
    notes: "北罗讷陡峭花岗岩坡是西拉的故乡，罗第丘可混酿少量维欧尼增添花香。",
  },
  {
    id: "bx-dry-white",
    code: "样酒 16",
    region: "波尔多",
    grape: "长相思",
    color: "白葡萄酒",
    appearance: "浅柠檬黄",
    acidity: "高",
    tannin: "无",
    body: "中等偏饱满",
    alcohol: "中",
    clues: ["长相思的青草柑橘骨架，但口感更丰腴", "橡木桶发酵带来圆润质感", "余味有燧石般的矿物咸鲜"],
    aromas: ["青草", "鹅莓", "柠檬", "橡木燧石"],
    notes: "佩萨克-雷奥良风格干白以长相思混酿少量赛美蓉，经橡木桶后比卢瓦尔长相思更丰满。",
  },
  {
    id: "bg-grand-cru",
    code: "样酒 17",
    region: "勃艮第",
    grape: "黑皮诺",
    color: "红葡萄酒",
    appearance: "中等宝石红",
    acidity: "高",
    tannin: "中",
    body: "中等偏饱满",
    alcohol: "中高",
    clues: ["比村级更集中、余韵超长", "红色水果与高级香料交织", "单宁如丝绸般细密"],
    aromas: ["草莓", "牡丹", "丁香", "松露"],
    notes: "特级园黑皮诺在浅颜色外表下拥有惊人的浓缩度与陈年层次。",
  },
  {
    id: "np-sb",
    code: "样酒 18",
    region: "纳帕",
    grape: "长相思",
    color: "白葡萄酒",
    appearance: "浅柠檬黄",
    acidity: "中高",
    tannin: "无",
    body: "中等",
    alcohol: "中高",
    clues: ["比旧世界长相思酒体更丰满", "带轻微橡木与甜瓜气息", "草本感被熟果包裹"],
    aromas: ["蜜瓜", "西柚", "青草", "无花果"],
    notes: "纳帕长相思（部分标 Fumé Blanc）常有轻微橡木接触，风格圆润。",
  },
];
